name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Replace Placeholders with Secrets
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          sed -i 's|{{FIREBASE_API_KEY}}|'"$FIREBASE_API_KEY"'|g' index.html
          sed -i 's|{{FIREBASE_AUTH_DOMAIN}}|'"$FIREBASE_AUTH_DOMAIN"'|g' index.html
          sed -i 's|{{FIREBASE_DATABASE_URL}}|'"$FIREBASE_DATABASE_URL"'|g' index.html
          sed -i 's|{{FIREBASE_PROJECT_ID}}|'"$FIREBASE_PROJECT_ID"'|g' index.html
          sed -i 's|{{FIREBASE_STORAGE_BUCKET}}|'"$FIREBASE_STORAGE_BUCKET"'|g' index.html
          sed -i 's|{{FIREBASE_MESSAGING_SENDER_ID}}|'"$FIREBASE_MESSAGING_SENDER_ID"'|g' index.html
          sed -i 's|{{FIREBASE_APP_ID}}|'"$FIREBASE_APP_ID"'|g' index.html
          sed -i 's|{{FIREBASE_MEASUREMENT_ID}}|'"$FIREBASE_MEASUREMENT_ID"'|g' index.html

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
